FROM kaixhin/cuda-theano:8.0

UN echo "export PATH=$PATH" >> /etc/profile && \
    echo "ldconfig" >> /etc/profile
RUN apt-get update && apt-get install -y openssh-server && apt-get install sudo
RUN mkdir /var/run/sshd
# set root password to root - change this to whatver
RUN echo 'root:Db340934' | chpasswd
# configure sshd to let root login
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

# expose SSH port
EXPOSE 22

RUN service ssh restart
RUN apt-get install -y sudo --no-install-recommends apt-utils
WORKDIR /root

# this is where we will mount a directory to get inputs/outputs without having to ssh every time
RUN mkdir /root/inputs
RUN mkdir /root/outputs

RUN pip3 install numpy scikit-learn
RUN apt-get install -y vim tmux && apt-get update
RUN echo "if [[ -z \"$TMUX\" ]] && [ \"$SSH_CONNECTION\" != \"\" ]; then" >> ~/.bashrc \
    echo "   tmux attach-session -t $USER || tmux new-session -s $USER \; split-window -v \; attach" >> ~/.bashrc \
    echo "fi" >> ~/.bashrc

WORKDIR /root
CMD ["/usr/sbin/sshd", "-D"]
