# Remote# Remote debug enabled container. IDE and code on host/network, environment
# isolated in Docker. Tested with PyCharm 17.2 Professional Edition.
FROM tensorflow/tensorflow:1.4.0-rc1-devel-gpu-py3

RUN echo "export PATH=$PATH" >> /etc/profile && \
    echo "ldconfig" >> /etc/profile
RUN apt-get update && apt-get install -y openssh-server && apt-get install sudo
RUN mkdir /var/run/sshd
# set root password to root - change this to whatver
RUN echo 'root:root' | chpasswd
# configure sshd to let root login
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

# expose SSH port
EXPOSE 22

RUN service ssh restart
RUN apt-get install -y sudo --no-install-recommends apt-utils python3-pip python3-dev
WORKDIR /root

# this is where we will mount a directory to get inputs/outputs without having to ssh every time
RUN mkdir /root/inputs
RUN mkdir /root/outputs

RUN pip3 install numpy
RUN apt-get install -y vim tmux && apt-get update

WORKDIR /root
CMD ["/usr/sbin/sshd", "-D"]


