# Start with CUDA Theano base image
FROM kaixhin/cuda-theano:8.0

# Install bleeding-edge Lasagne
RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
# SSH support
RUN echo "export PATH=$PATH" >> /etc/profile && \
    echo "ldconfig" >> /etc/profile
RUN apt-get update && apt-get install -y openssh-server && apt-get install sudo
RUN mkdir /var/run/sshd
# set root password to root - change this to whatver
RUN echo 'root:Db340934' | chpasswd
# configure sshd to let root login
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

# expose SSH port
EXPOSE 22

RUN service ssh restart

RUN apt-get install -y sudo pkg-config apt-utils pkg-config --no-install-recommends libpng-dev
RUN apt-get upgrade -y
RUN apt-get install -y vim wget git unzip
RUN apt-get install -y libfreetype6 libfreetype6-dev pkg-config
RUN pip install freetype-py
RUN apt-get build-dep -y python-matplotlib
RUN pip install numpy scikit-learn scikit-image matplotlib
# this is where we will mount a directory to get inputs/outputs without having to ssh every time
RUN mkdir /root/inputs
RUN mkdir /root/outputs
# this is where our projects go
# notebook should run on the background as well as sshd
COPY start.sh /
RUN chmod +x /start.sh
# set default directory we enter on logon to home directory

RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
WORKDIR /root
RUN ln -s /start.sh /root/start_notebook.sh
CMD ["/usr/sbin/sshd", "-D"]

