FROM nvidia/cuda:8.0-cudnn5-devel

ENV THEANO_VERSION 0.9.0
LABEL com.nvidia.theano.version="0.9.0"
ENV PYGPU_VERSION 0.6.9
USER root
# Install bleeding-edge Lasagne
RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip

#ssh
RUN apt-get install -y openssh-server && apt-get install sudo
RUN mkdir /var/run/sshd
# set root password to root - change this to whatver
RUN echo 'root:root' | chpasswd
# configure sshd to let root login
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

# expose SSH port
EXPOSE 22

RUN service ssh restart
WORKDIR /root

# this is where we will mount a directory to get inputs/outputs without having to ssh every time
RUN mkdir /root/inputs
RUN mkdir /root/outputs
RUN apt-get install -y tmux

WORKDIR /root
CMD ["/usr/sbin/sshd", "-D"]
